services:
  deliverer:
    class: Mannion007\WaffleFactory\Delivery\RestfulApiDelivery
    arguments:
      - '@maker'

  maker:
    class: Mannion007\WaffleFactory\Maker\HomeMadeWaffleMaker
    arguments:
      - '@batter-dispenser'
      - '@cheapo-oven'
      - '@mysql-delivery'

  cheapo-batter-dispenser:
    class: Mannion007\WaffleFactory\BatterDispenser\CheapoWaffleBatterPacket

  premium-batter-dispenser:
      class: Mannion007\WaffleFactory\BatterDispenser\PremiumWaffleBatterPacket

  cheapo-oven:
    class: Mannion007\WaffleFactory\Oven\CheapoOven

  mysql-delivery:
    class: Mannion007\WaffleFactory\Delivery\MysqlDelivery
    arguments:
      - '127.0.0.1'
      - '3306'
      - 'waffles'
      - 'toor'
      - 'toor'

  redis-delivery:
      class: Mannion007\WaffleFactory\Delivery\RedisDelivery
      arguments:
        - '127.0.0.1'
        - '6379'