services:
  deliverer:
    class: Mannion007\WaffleFactory\Delivery\RestfulApiDelivery
    arguments:
      - '@home-maker'

  home-maker:
    class: Mannion007\WaffleFactory\Maker\WaffleMaker
    arguments:
      - '@cheapo-batter-dispenser'
      - '@cheapo-oven'
      - '@mysql-delivery'

  commercial-maker:
      class: Mannion007\WaffleFactory\Maker\WaffleMaker
      arguments:
        - '@premium-batter-dispenser'
        - '@commercial-oven'
        - '@redis-delivery'

  cheapo-batter-dispenser:
    class: Mannion007\WaffleFactory\BatterDispenser\CheapoWaffleBatterPacket

  premium-batter-dispenser:
      class: Mannion007\WaffleFactory\BatterDispenser\PremiumWaffleBatterPacket

  cheapo-oven:
    class: Mannion007\WaffleFactory\Oven\CheapoOven

  commercial-oven:
      class: Mannion007\WaffleFactory\Oven\CommercialoOven

  mysql-delivery:
    class: Mannion007\WaffleFactory\Delivery\MysqlDelivery
    arguments:
      - '127.0.0.1'
      - '3306'
      - 'waffles'
      - 'toor'
      - 'toor'

  redis-delivery:
      class: Mannion007\WaffleFactory\Delivery\RedisDelivery
      arguments:
        - '127.0.0.1'
        - '6379'